services:
  - type: web
    name: crm-backend
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: PYTHONUTF8
        value: "1"
      - key: DATABASE_URL
        fromDatabase:
          name: crm-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"

  - type: static
    name: crm-frontend
    buildCommand: "npm install && npm run build"
    publishPath: "./dist"
    envVars:
      - key: VITE_API_URL
        value: https://crm-backend.onrender.com/api/v1

databases:
  - name: crm-db
    databaseName: taskpro_db
    user: taskpro_admin